export const AUDIT_ACTIONS = Object.freeze({
  LEAD_CREATED: 'lead.created',
  LEAD_UPDATED: 'lead.updated',
  LEAD_ASSIGNED: 'lead.assigned',
  LEAD_STATUS_CHANGED: 'lead.status_changed',
  LEAD_PRIORITY_CHANGED: 'lead.priority_changed',
  LEAD_CONVERTED: 'lead.converted',
  LEAD_DELETED: 'lead.deleted',
  CUSTOMER_CREATED: 'customer.created',
  CUSTOMER_UPDATED: 'customer.updated',
  CUSTOMER_DELETED: 'customer.deleted',
  DEAL_CREATED: 'deal.created',
  DEAL_UPDATED: 'deal.updated',
  DEAL_ASSIGNED: 'deal.assigned',
  DEAL_STAGE_CHANGED: 'deal.stage_changed',
  DEAL_WON: 'deal.won',
  DEAL_LOST: 'deal.lost',
  DEAL_REOPENED: 'deal.reopened',
  DEAL_DELETED: 'deal.deleted',
  ACTIVITY_CREATED: 'activity.created',
  ACTIVITY_UPDATED: 'activity.updated',
  ACTIVITY_COMPLETED: 'activity.completed',
  ACTIVITY_DELETED: 'activity.deleted',
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_STATUS_CHANGED: 'user.status_changed',
  USER_DEACTIVATED: 'user.deactivated',
  CONFIG_UPDATED: 'config.updated',
});

export const ENTITY_TYPES = Object.freeze({
  LEAD: 'Lead',
  CUSTOMER: 'Customer',
  DEAL: 'Deal',
  ACTIVITY: 'Activity',
  USER: 'User',
  CONFIG: 'Config',
});
